### ISSUE TITLE
Matrix Chat Raum offline

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#102]
Also: neuen Chatraum anlegen und mit Slack verknüpfen.

**Comment by MTRNord** [comment]
Hm? Wie meinst du offline? Der Raum existiert noch. Oder ist der Server womit du den erstellt hattest nicht mehr existent?

**Comment by silberzwiebel** [comment]
Ja, ich hatte meinen Account auf matrix.allmende.io und das funktioniert wohl leider nicht mehr. Zumindest der Badge im README zeigt auch an, dass der Raum offline ist ...
