### ISSUE TITLE
“Heute” im Diagramm markieren

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/klimawatch#14]
Ich glaube es wäre hilfreich, wenn das aktuelle Jahr oder der Zeitpunkt bis zu dem offizielle Daten verfügbar sind, visuell markiert werden würde. Vielleicht mit einem vertikalen Strich.

**Comment by silberzwiebel** [comment]
Ist in den neueren Plots drin, danke für die Idee!
