### ISSUE TITLE
NutzerInnen sollen Parisziele selber einzeichnen können

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#15]
Erst danach werden die tatsächlichen Parisziele gezeigt. Führt vermutlich zu größerer Überraschung. Es gibt dazu wohl eine Library, die vom WDR genutzt wurde/wird.

**Comment by silberzwiebel** [comment]
Implementiert durch @marcel12bell, danke!

**Comment by ubergesundheit** [comment]
Ist aber nirgendwo erklärt, dass das geht

**Comment by silberzwiebel** [comment]
Der momentane Text davor reicht vielleicht?

**Comment by ubergesundheit** [comment]
jo
