### ISSUE TITLE
Email verschleiern

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/klimawatch#27]
Die Emailadresse sollte aus SPAM Gründen verschleiert werden. Ich verwende seit mehreren Jahren dieses Snippet auf meiner Webseite und das funktioniert gut.

https://github.com/ubergesundheit/ubergesundheit.github.io/blob/master/js/geraldpapeio.js

**Comment by silberzwiebel** [comment]
Hatte ich im Hinterkopf, wollte für erstes "Release" aber Kontaktmöglichkeit haben. Klingt nach einer guten Lösung.
