### ISSUE TITLE
Rest der Seite erst nach you-draw-it anzeigen

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#32]
NutzerInnen sollen erst etwas einzeichnen, dann wird erst der Rest der Seite geladen

**Comment by ubergesundheit** [comment]
Könnte dazu führen, dass Leute einfach wieder weggehen wenn entweder:

- Kein Javascript aktiviert ist
- Keine Lust was einzuzeichnen besteht

**Comment by tomsrocket** [comment]
Was Gerald sagt +1

**Comment by MTRNord** [comment]
Lösungsideen:
1. Default wird alles angezeigt und nur JS blendet den rest (via css class o. ä. aus) damit ist alles da wenn JS aus ist.
2. Überspringen Knopf für die Faulen der aber auffälig ist aber nicht zu auffälig (also sichtbarer als das X in einer handy werbung aber auch nicht einen anschreit^^)

**Comment by silberzwiebel** [comment]
Wenn kein Javascript aktiviert ist, dann dürfte sowieso kein Plot angezeigt werden, oder?
Überspringen-Knopf ist vielleicht gar nicht so verkehrt. Die ganze Idee ist v.a. dazu da, die Interaktion der NutzerInnen zu erhöhen. Vielleicht ist das ja gar nicht sinnvoll?

**Comment by thunfischtoast** [comment]
Ohne Javascript aktuell keine Plots. Als Alternative könnte man statische Plots (als Bild) einbinden, die dann vom Javascript ausgeblendet werden.

**Comment by silberzwiebel** [comment]
Wir lassen es erstmal so wie es ist. Für "kein Javascript" kann jemand evtl. ein neues Issue erstellen, bei Interesse.
