### ISSUE TITLE
you-draw-it Daten automatisch einlesen

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#33]
Die Datenreihe wird vom python-Skript generiert, der Rest ist noch statisch in einer anderen Datei. Evtl. den statischen Rest auch vom python-skript schreiben lassen?

**Comment by marcel12bell** [comment]
@silberzwiebel falls du das machst, sollten wir ggf. noch mal überlegen das youdrawit zu wechseln... siehe https://github.com/EE2dev/you-draw-it und https://bl.ocks.org/ee2dev/e085741d2376c4c12800c855f381266d dann haben wir noch mehr configs drin und auch andere Charts (Balkendiagram), bzw. auch Fragen...

**Comment by silberzwiebel** [comment]
Habe keine Ahnung von Javascript. Von daher freue ich mich hier über Pull Requests :)
In Python kann ich aber gerne statischen Code mit in die Dateien reinschreiben lassen.
