### ISSUE TITLE
you-draw-it zeichnet nicht zuverlässig

### ISSUE THREAD

**Issue by quassy** [codeformuenster/klimawatch#35]
Beim Selbstzeichnen (mit Touchpad) sind die selbstgezeichneten Linien teils nicht durchgängig, sodass die automatische Anzeige der Parisziele nicht auslöst. Man muss schon relativ langsam zeichnen, damit es klappt. 

![Screenshot_2019-12-03 Klimaschutz in Münster(1)](https://user-images.githubusercontent.com/369996/70078727-83ca2f00-1603-11ea-8839-a0d406bedb31.png)

Genauso ist einem nicht unbedingt klar, dass man mit seiner Linie den kompletten x-Bereich abdecken muss: Zeichne ich von heute auf 2030 steil runter, löst die automatische Anzeige ebenfalls nicht aus.

![Screenshot_2019-12-03 Klimaschutz in Münster](https://user-images.githubusercontent.com/369996/70078677-685f2400-1603-11ea-9065-0b7161efff11.png)

(Firefox Devel auf macOS Catalina)

**Comment by tomsrocket** [comment]
Auf dem chrome browser auf meinem lg g6 Handy mit android 9 geht übrigens gar kein zeichnen. Da verschiebt man mit dem finger im graphen einfach nur die seite, nix mit zeichnen. :(

**Comment by MTRNord** [comment]
> 
> 
> Auf dem chrome browser auf meinem lg g6 Handy mit android 9 geht übrigens gar kein zeichnen. Da verschiebt man mit dem finger im graphen einfach nur die seite, nix mit zeichnen. :(

Das ist bei mir in firefox am pc (windows) genau wie du es beschreibst.

**Comment by silberzwiebel** [comment]
Das mit dem nicht-durchgängigen Zeichnen habe ich bei mir auch schon bemerkt und fand ich ungünstig. Das man bis 2050 zeichnen muss, könnte man im Text hinzufügen?

Das gar nicht gezeichnet werden kann, sollte natürlich nicht vorkommen. Vielleicht wechseln wir aber ohnehin die Implementierung, s. https://github.com/codeformuenster/klimawatch/issues/33

@marcel12bell weißt Du vielleicht Abhilfe zu obigen Problemen?

**Comment by thunfischtoast** [comment]
In `hugo/assets/js/you_draw_it_template.js` reagiert dieser Code auf das Eingabeevent:
`  var drag = d3.drag()
    .on('drag', function(){
      var pos = d3.mouse(this)
      var year = clamp({{ .start_year_draw  }}+1, {{ .end_year_chart }}, c.x.invert(pos[0]))
      var value = clamp(0, c.y.domain()[1], c.y.invert(pos[1]))

      yourData.forEach(function(d){
        if (Math.abs(d.year - year) < .5){
          d.value = value
          d.defined = true
        }
      })

      yourDataSel.at({d: line.defined(ƒ('defined'))(yourData)})

      if (!completed && d3.mean(yourData, ƒ('defined')) == 1){
        completed = true
        clipRect.transition().duration(1000).attr('width', c.x({{ .end_year_chart }}))
      }
    })`

Hier könnte man, wenn ein Punkt gesetzt wird, alle vorhergehenden, nicht gesetzten Punkte linear interpolieren. Wenn man einen Punkt auf 0 Tonnen setzt sollten alle nachfolgenden ebenfalls auf 0 Tonnen gesetzt werden.

**Comment by silberzwiebel** [comment]
@MTRNord und @tomsrocket mögt ihr das neue you-draw-it, dass @marcel12bell im PR #46  hinzugefügt hat, mal testen, ob es bei euch überhaupt funktioniert? Und @quassy, behebt das neue you-draw-it auch Deine Probleme?

Unter diesem Link erreichbar: https://deploy-preview-46--klimawatch.netlify.com/kommunen/koeln/

**Comment by tomsrocket** [comment]
Linie zeichnen funktioniert jetzt bei mir! 👍
![Capture+_2020-01-05-12-38-45](https://user-images.githubusercontent.com/6351193/71780327-77017800-2fc1-11ea-82aa-5fbc788ab06e.png)

**Comment by marcel12bell** [comment]
@tomsrocket so wie es aussieht, hat das @thunfischtoast mit https://github.com/codeformuenster/klimawatch/commits/new-youdrawit-v2 gefixt.. ggf. muss man da dann nur noch etwas mehr Breite per css geben, dann stimmt es. @silberzwiebel Wie sieht es mit nem Merge aus?

**Comment by silberzwiebel** [comment]
Siehe [mein Kommentar](https://github.com/codeformuenster/klimawatch/pull/46#issuecomment-570902454) im PR #46.

**Comment by silberzwiebel** [comment]
@tomsrocket @MTRNord @quassy funktioniert es jetzt besser? https://klimawatch.codefor.de/kommunen/muenster/

Wenn ja, gerne issue schließen :)

**Comment by MTRNord** [comment]
Firefox windows 10 klappt nun bei mir :D

**Comment by silberzwiebel** [comment]
Falls das Problem noch existiert, gerne wieder öffnen.
