### ISSUE TITLE
Dateigröße Plotly

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/klimawatch#37]
https://github.com/plotly/plotly.js/blob/master/BUILDING.md

-> @silberzwiebel -> Welche Parts der library brauchen wir?

Implementierung -> So oder so ähnlich https://github.com/budparr/hugo-pipes-parcel

**Comment by silberzwiebel** [comment]
Nehme an, die folgenden:

- `core` (?)
- `scatter` (oder `scattergl`? Benutzt dann webGL und ist wohl schneller?)
- `treemap` (für die Modulvisualisierung, da bin ich gerade dran)
