### ISSUE TITLE
you-draw-it Y-Achsenbeschriftung

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/klimawatch#39]
Die Y-Achse des you-draw-it sollte statt ` tausend Tonnen` nur einmal oben an der obersten Spitze ` millionen Tonnen` stehen haben und dann an den Ticks `0,5`, `1`, `1,5` und `2,0` verwenden. 

Für mobil wäre dadurch das Diagramm deutlich breiter

**Comment by marcel12bell** [comment]
@ubergesundheit du kannst in der json die Anzahl der Ticks konfigurieren...

**Comment by silberzwiebel** [comment]
Oder die Achsenbeschriftung von oben nach unten schreiben? Oder abkürzen: tT?

**Comment by marcel12bell** [comment]
@silberzwiebel das geht mit dem "unit" Parameter in der json...

**Comment by silberzwiebel** [comment]
@ubergesundheit Ist es nun besser mit der neuen you-draw-it Version? https://klimawatch.codefor.de/kommunen/muenster/

Falls ja, gerne issue schließen :)

**Comment by ubergesundheit** [comment]
sieht mega aus :heart:
