### ISSUE TITLE
einfaches generieren der Seite

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#5]
also ohne manuelles Kopieren des div-Elements

**Comment by ubergesundheit** [comment]
Es sollte definitv möglich sein, das ganze per CI (zb Github Actions, Travis, Circle, etc...) bauen zu lassen, so dass die Seite automatisch bei jedem Commit gebaut wird. 

Wenn ich keine Lust mehr auf verkehrsunfaelle habe, schau ich mir das mal an :+1:

**Comment by silberzwiebel** [comment]
Sehr schön :)
Bisher ist es manuell geschriebenes HTML. Leider muss man eine ID im `<div>` anpassen, wenn man eine neue Version des Plots reinladen will. Aber je nachdem, wie wir andere Dinge realisieren, sollten wir das vielleicht ohnehin auf eine andere Basis stellen.
