### ISSUE TITLE
Gesamtemissionen Deutschland 2019 für Paris-Budget-Berechnung nutzen

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#69]
Momentan wird noch die jeweils letzte Zahl einer Kommune genommen und als Emissionen für 2019 angenommen (weil https://scilogs.spektrum.de/klimalounge/wie-viel-co2-kann-deutschland-noch-ausstossen/ von Anfang *2019* ausgeht). Schöner wäre es, hier die Gesamtzahl der Emissionen 2019 für ganz Deutschland zu nehmen.

**Comment by jonek** [comment]
Soweit ich weiß dauert es ca. 15 Monate bis die notwendigen Daten eines Jahres verfügbar sind.
D.h. für 2019 werden alle Daten erst in Q2 2021 vorliegen.
Daraus folgt, dass wir für diese "Zwischenzeit" immer eine sinnvolle Annahme treffen müssen.

Eine Erklärung, warum die Daten so lange brauchen, findet sich z.B. hier: https://www.thru.de/index.php?id=418#c1148

**Comment by silberzwiebel** [comment]
Ah, okay. Dazu passt, dass die Zahl für 2018 für Münster auch erst vorletzte Woche veröffentlich wurde. Also ist vermutlich der jetzige Ansatz der sinnvollste?
