### ISSUE TITLE
Umstellung auf klimawatch.de

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/klimawatch#73]
- [x] sicherstellen, dass alte Links (mit klimawatch.codefor.de) korrekt weiterleiten
- [ ] hugo config.toml anpassen
- [x] ggf. netlify deployment anpassen
- [x] klimawatch.de entsprechend einstellen

**Comment by ubergesundheit** [comment]
Kann mich frühestens am Samstag kümmern.

DNS sollte so konfiguriert sein wenn klimawatch.de die Hauptdomain sein soll:

Wenn der Domainhoster ALIAS records kann, dann:

klimawatch.de ALIAS klimawatch.netlify.com. 

wenn nicht, dann:
klimawatch.de A 104.198.14.52

Und dann noch:
www CNAME klimawatch.netlify.com.

**Comment by ubergesundheit** [comment]
Das hier steht auch noch auf netlify

```
# These rules will change if you change your site’s custom domains or HTTPS settings

# Redirect domain aliases to primary domain
https://klimawatch.de/* https://www.klimawatch.de/:splat 301!
https://klimawatch.codefor.de/* https://www.klimawatch.de/:splat 301!

# Optional: Redirect default Netlify subdomain to primary domain
https://klimawatch.netlify.com/* https://www.klimawatch.de/:splat 301!

**Comment by gerbsen** [comment]
Ich hab das hier eingestellt:

    wenn nicht, dann:
    klimawatch.de A 104.198.14.52

    Und dann noch:
    www CNAME klimawatch.netlify.com.

**Comment by ubergesundheit** [comment]
Scheint in Ordnung gewesen zu sein. Alles was ich gerade noch gemacht habe:
- Auf netlify die primary domain umgestellt
- nochmal den letzten build angestoßen

:rotating_light: damit ist jetzt aber klimawatch.codefor.de kaputt.. Vielleicht ist das hier ne abhilfe: https://github.com/codeformuenster/klimawatch/issues/73#issuecomment-589947663

**Comment by silberzwiebel** [comment]
Danke, habe die redirects hinbekommen. War zu ungeduldig, deshalb viele häßliche PRs: #78 , #79, #80 . Jetzt sollte fast alles unter klimawatch.de klappen und alte Links passend umgeleitet werden!
