### ISSUE TITLE
Quellen und Gradziel für paris-limits.md 

### ISSUE THREAD

**Issue by kolossos** [codeformuenster/klimawatch#85]
Hat noch jemand Quellen für das CO2-Budget in paris-limits.md ? 
Dazugehören würde aus meiner Sicht auch die Frage ob damit 1.5 °C oder 2 °C gemeint ist und mit welcher Wahrscheinlichkeit dieses Temperaturziel erreicht wird.

**Comment by kolossos** [comment]
Ich glaube ihr meint die Tabelle: 
https://de.wikipedia.org/wiki/CO2-Budget#Ausgangslage
Aus dem 
Die angegebenen 800t sind dann genau zwischen 1.5 und 2°C also 1,75 °C mit einer Wahrscheinlichkeit von 66% das wir da drunter bleiben. 
Die Tabelle entstammt wiederum dem IPCC SR1.5 Chapter 2 Table 2.2:
https://www.ipcc.ch/sr15/

**Comment by kolossos** [comment]
Noch etwas anderes, wobei ich nicht weiß ob das zielführend ist:
Auch wenn mir das klar ist, sollte man vielleicht noch  erklären warum man sich für die Verteilungsmethode mit einem gleichen CO2-Budget pro Kopf entschieden hat (Klimagerechtigkeit).

Würde man pro Land ein Pro Kopf Budget ab 1990 (erster Klimagimpfel) als Maßstab nehmen,  so müssten wir ab morgen negativ emitieren. 

Ein anderes Verfahren wäre, dass man aus dem globale Budget einen globalen Senkungspfad berechnet (x-Prozent Rückgang im CO2-Ausstoss pro Jahr) . Damit wären dann alle Länder zur selben Zeit bei Null.  Die entwickelten Länder die über die vergangen Jahr von dem erhöhten Einsatz von fossilen Energien dürften also noch lange Zeit pro Kopf mehr ausstoßen als arme Länder. Es ist klar erkennbar dass dieses Verfahren von den ärmeren Ländern als unrecht angesehen würde und somit nicht anerkannt würde.    

Wie gesagt, keine Ahnung, ob die Thematik zielführend ist oder eher verwirrt.

**Comment by thunfischtoast** [comment]
Die Primärquelle war hier soweit ich weiß https://scilogs.spektrum.de/klimalounge/wie-viel-co2-kann-deutschland-noch-ausstossen/, was auf der Markdown-Seite auch verlinkt ist. Möglicherweise ist das durch die Farbgebung nicht so offensichtlich. Beantwortet der Artikel eventuell schon einen Teil deiner Frage?

**Comment by kolossos** [comment]
Jupp, jetzt kann man die Links wirklich nicht mehr übersehen. Der Artikel von Ramstorf ist natürlich super. Danke.
