### ISSUE TITLE
Ansprechparnter für Stadt im Template

### ISSUE THREAD

**Issue by gerbsen** [codeformuenster/klimawatch#87]
Es wäre für externe Interessierte extrem nützlich, wenn man für die einzelnen Städte eine Kontaktemail/person hätte, an die man sich für weitere Fragen wenden könnte.

**Comment by silberzwiebel** [comment]
Hier im Template bzw. den einzelnen Kommunenseiten zu ändern: https://github.com/codeformuenster/klimawatch/tree/master/hugo/content/kommunen
